### ISSUE TITLE
Crash in Chronicles of Myrtana

### ISSUE THREAD

**Issue by AnonymisedFellow** [szapp/FreeAiming#5]
This plugin causes crashes whenever i try to cook, use alchemy table, anything with recipes really. I zeroed it down to FreeAiming.vdf..

**Comment by AnonymisedFellow** [comment]
It also crashes while receiving fall damage/air damage, probably because in chronicles it has been changed from the g2nor

**Comment by AnonymisedFellow** [comment]
Air damage can be tested by receving hits from golems and probably trolls

**Comment by szapp** [comment]
Thank you for your effort in reporting this incompatibility!

This is a known issue and cannot be addressed on this side. It is due to Chronicles of Myrtana butchering core libraries which breaks any past and future compatibility efforts.

There has been no visible efforts from their side to fix their work or pick up the maintainers' offer to work together on incorporating their adjustments into the official libraries. Hence, I unfortunately don't have the time to chase other people's mistakes and/or their lack of communication/collaboration.

To relay the standing offer for collaboration to the creators of Chronicles of Myrtana is the only option at that time.
